version: "3.3"

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    command: sh -c "yarn install && yarn start"
    ports: 
      - 8000:3000
      - 8001:5000