version: "3.3"

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    entrypoint: yarn
    command: start
    ports: 
      - 8000:3000
      - 8001:5000